services:
  payments:
    build:
      context: .
    ports:
      - '8080:8080'
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: 'mariadb'
    restart: always
    environment:
      - 'MARIADB_DATABASE=payments'
#      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=asW4oqyvvpySYeSdxcDD'
#      - 'MARIADB_USER=root'
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3